theme: jekyll-theme-leap-day
title: Loreen's github pages
description: Interesting assignments and data visualizations.
![Data Visualization] (https://hbr.org/2016/06/visualizations-that-really-work)
